highlighter: rouge
relative_permalinks: false

exclude: [
  'Gemfile',
  'Gemfile.lock',
  '*.sublime-project',
  'Rakefile',
  'README.md'
]

full-title: "King'ori's Bible Study"
short-title: "Bible Study"
license: "http://creativecommons.org/licenses/by-nc-nd/4.0/"
description: |-
  Daily collection and exploration of the God's authoritative Word which we
  should study because 'All scripture is given by inspiration of God, and is
  profitable for doctrine, for reproof, for correction, for instruction in
  righteousness (2 Timothy 3:16 - KJV).

author:
  fullname: "King'ori Maina"
  website: "http://kingori.co"
  twitter: "itskingori"

markdown: kramdown
kramdown:
  input: GFM
  auto_id_prefix: ''
  auto_id_stripping: true
  auto_ids: true
  entity_output:  as_char
  footnote_backlink: '&8617;'
  footnote_nr: 1
  hard_wrap: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
