markdown: redcarpet
pygments: true
baseurl: /systematic-theology

redcarpet:
  extensions: ['no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'tables']

exclude: ['Gemfile', 'Gemfile.lock', '*.sublime-project', 'README.md']

name: "Bible Study"
description: "Daily collection and exploration of the God's authoritative word by King'ori J. Maina"
author:
  fullname: "King'ori J. Maina"
  website: "http://kingori.co"
