name: "King'ori's Bible Study"
markdown: redcarpet
pygments: true
baseurl: /systematic-theology

redcarpet:
  extensions: ['no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'tables']

exclude: ['Gemfile', 'Gemfile.lock', '*.sublime-project', 'README.md']
